### ISSUE TITLE
Fix 'Trailing spaces' issue in .github\dependabot.yml

### ISSUE THREAD

**Issue by marcusturewicz** [marcusturewicz/jsonvalidate.net#111]
[CodeFactor](https://www.codefactor.io/repository/github/marcusturewicz/jsonvalidate.net/overview/main) found an issue: Trailing spaces

It's currently on:
[.github\dependabot.yml:10
](https://www.codefactor.io/repository/github/marcusturewicz/jsonvalidate.net/source/main/.github/dependabot.yml#L10)Commit b1528d903ad9cf20b0fe78bc898014ccc270a45e

**Comment by felipedotcom** [comment]
did it
