### ISSUE TITLE
Does not provide fallback content when JavaScript is not available

### ISSUE THREAD

**Issue by marcusturewicz** [marcusturewicz/jsonvalidate.net#76]
From lighthouse audit, PWA section:

> Does not provide fallback content when JavaScript is not availableThe page body should render some content if its scripts are not available.
> 
> Your app should display some content when JavaScript is disabled, even if it's just a warning to the user that JavaScript is required to use the app. Learn more.

![image](https://user-images.githubusercontent.com/24448509/66316544-87ea1100-e920-11e9-905c-6535247f44f6.png)

More info can be found here https://developers.google.com/web/tools/lighthouse/audits/no-js?utm_source=lighthouse&utm_medium=devtools

**Comment by souravdasslg** [comment]
Hey @marcusturewicz , can you please elaborate on what needs to be rendered if the Javascript is not available? Is "Javascript not available" is sufficient?

**Comment by marcusturewicz** [comment]
Good point. How about:

"JavaScript is disabled. JavaScript must be enabled for this site to work correctly."

**Comment by souravdasslg** [comment]
I guess that'll do great. I'd like to work on that :)

**Comment by marcusturewicz** [comment]
Great thanks, go for it!
