### ISSUE TITLE
Links to cross-origin destinations are unsafe

### ISSUE THREAD

**Issue by marcusturewicz** [marcusturewicz/jsonvalidate.net#77]
From lighthouse audit:

> Add `rel="noopener"` or `rel="noreferrer"` to any external links to improve performance and prevent security vulnerabilities. …jsonvalidate.net/issues(github.com)

![image](https://user-images.githubusercontent.com/24448509/66316441-5b35f980-e920-11e9-91f4-1b6136c00d5b.png)

This is the offending line:

https://github.com/marcusturewicz/jsonvalidate.net/blob/c527fed85f2907db5a919d325adaa7c11ac0f1bd/src/JsonValidate/Shared/MainLayout.razor#L21

More info can be found here https://developers.google.com/web/tools/lighthouse/audits/noopener?utm_source=lighthouse&utm_medium=devtools

**Comment by cweave** [comment]
I'll snab this
