### ISSUE TITLE
The page does not contain a heading, skip link, or landmark region

### ISSUE THREAD

**Issue by marcusturewicz** [marcusturewicz/jsonvalidate.net#83]
![image](https://user-images.githubusercontent.com/24448509/66339914-cdbcce80-e94c-11e9-95a5-07af976e0ac9.png)

More info can be found here https://dequeuniversity.com/rules/axe/3.1/bypass?application=lighthouse

**Comment by Pr0ftR3gret** [comment]
I'd like to take this.

**Comment by marcusturewicz** [comment]
Go for it!!

**Comment by Pr0ftR3gret** [comment]
I read through the link you provided and understand the rule it's looking to satisfy, but I'm unsure where you are getting the screenshot you posted. Is there some sort of analyzer you are running your HTML through?

**Comment by marcusturewicz** [comment]
This was generated by running chrome devtools audit (lighthouse) on www.jsonvalidate.net

https://developers.google.com/web/tools/lighthouse

**Comment by Pr0ftR3gret** [comment]
Thank you, I was running axe and expecting those results. If you follow the link you posted and hit tab on that page you should see their implementation of "skip to content". Would you like something visible like that or hidden with css?

**Comment by marcusturewicz** [comment]
I think the solution is to include a <main> tag in the MainLayout.razor. See if that fixes it
